name: taxiwalahost
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  another_stepper: ^1.2.2
  charts_flutter: ^0.12.0
  flutter_switch: ^0.3.2
  cupertino_icons: ^1.0.6
  sliding_up_panel: ^2.0.0+1
  geolocator: ^10.1.0
  google_maps_flutter:
  geocoding: ^2.1.1
  carousel_slider: ^4.2.1
  location: ^5.0.3
  flutter_google_places: ^0.3.0
  five_pointed_star: ^1.0.3
  shared_preferences: ^2.0.1
  fluttertoast:
  another_flushbar:
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/images/







